[package]
name = "cargo-actions"
version = "0.1.0"
edition = "2021"
license = "MIT"
description = "create a CI github action"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.79"
auto-git = "0.1.0"
clap = { version = "4.4.18", features = ["derive"] }
console = "0.15.8"
dialogue = "0.0.0"
dialogue-macro = "0.2.2"
dialoguer = "0.11.0"
fs_extra = "1.3.0"
git2 = "0.18.1"
handlebars = "5.1.1"
serde = { version = "1.0.195", features = ["derive"] }
serde_json = "1.0.112"
serde_yaml = "0.9.30"
toml = "0.8.8"


[workspace]
members = ["packages/testA", "packages/testB", "testC"]
