[package]
name = "cargo-actions"
version = "0.1.0"
edition = "2021"
license = "MIT"
description = "create a CI github action"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
