name: CI
on:
  push:
    tags:
      - "v*"
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: publish
        run: |
          # cargo publish -p actions-templates --token ${{ secrets.CRATE_TOKEN }}
          cargo publish --token ${{ secrets.CRATE_TOKEN }}
